"""
Generate a list of 250 popular songs across different genres.
This provides the base song list that will be enriched with AI-generated moods and descriptions.
"""

# 250 popular songs across various genres and eras
# Format: "Song Title Artist Name"
SONG_QUERIES = [
    # Pop Classics
    "Billie Jean Michael Jackson",
    "Like a Prayer Madonna",
    "Umbrella Rihanna",
    "Rolling in the Deep Adele",
    "Shape of You Ed Sheeran",
    "Blinding Lights The Weeknd",
    "Levitating Dua Lipa",
    "Bad Guy Billie Eilish",
    "Watermelon Sugar Harry Styles",
    "drivers license Olivia Rodrigo",
    
    # Rock Classics
    "Bohemian Rhapsody Queen",
    "Stairway to Heaven Led Zeppelin",
    "Hotel California Eagles",
    "Sweet Child O' Mine Guns N' Roses",
    "Smells Like Teen Spirit Nirvana",
    "Wonderwall Oasis",
    "Mr. Brightside The Killers",
    "Seven Nation Army The White Stripes",
    "Boulevard of Broken Dreams Green Day",
    "Radioactive Imagine Dragons",
    
    # Happy/Upbeat Songs
    "Happy Pharrell Williams",
    "Walking on Sunshine Katrina and The Waves",
    "Good as Hell Lizzo",
    "Can't Stop the Feeling Justin Timberlake",
    "Uptown Funk Mark Ronson Bruno Mars",
    "Shake It Off Taylor Swift",
    "I Gotta Feeling Black Eyed Peas",
    "Don't Stop Me Now Queen",
    "September Earth Wind Fire",
    "Dancing Queen ABBA",
    "Good Vibrations The Beach Boys",
    "Celebration Kool and The Gang",
    "Three Little Birds Bob Marley",
    "Lovely Day Bill Withers",
    "Best Day of My Life American Authors",
    "On Top of the World Imagine Dragons",
    "Send Me On My Way Rusted Root",
    "Walking On Sunshine Katrina The Waves",
    "I'm Gonna Be (500 Miles) The Proclaimers",
    "Footloose Kenny Loggins",
    
    # Calm/Chill Songs
    "Weightless Marconi Union",
    "Clair de Lune Debussy",
    "Breathe Me Sia",
    "River Flows in You Yiruma",
    "The Night We Met Lord Huron",
    "Holocene Bon Iver",
    "Saturn Sleeping At Last",
    "Gymnopédie No 1 Erik Satie",
    "Sunset Lover Petit Biscuit",
    "To Build a Home The Cinematic Orchestra",
    "Mad World Gary Jules",
    "Skinny Love Bon Iver",
    "Chasing Cars Snow Patrol",
    "The A Team Ed Sheeran",
    "Say Something A Great Big World",
    "Let Her Go Passenger",
    "Falling Harry Styles",
    "Ocean Eyes Billie Eilish",
    "Vienna Billy Joel",
    "Landslide Fleetwood Mac",
    
    # Sad/Emotional Songs
    "Someone Like You Adele",
    "Fix You Coldplay",
    "Hurt Johnny Cash",
    "Everybody Hurts REM",
    "The Sound of Silence Simon Garfunkel",
    "Yesterday The Beatles",
    "Tears in Heaven Eric Clapton",
    "Hallelujah Jeff Buckley",
    "Black Pearl Jam",
    "Creep Radiohead",
    "Nothing Compares 2 U Sinead O'Connor",
    "The Scientist Coldplay",
    "When I Was Your Man Bruno Mars",
    "All Too Well Taylor Swift",
    "Back to Black Amy Winehouse",
    "Stay Rihanna",
    "See You Again Wiz Khalifa",
    "Before You Go Lewis Capaldi",
    "Somebody That I Used to Know Gotye",
    "Dancing On My Own Robyn",
    
    # Energetic/Stress Relief
    "Midnight City M83",
    "Thunderstruck AC/DC",
    "Eye of the Tiger Survivor",
    "Lose Yourself Eminem",
    "Stronger Kanye West",
    "Run the World Girls Beyoncé",
    "Pump It Black Eyed Peas",
    "Enter Sandman Metallica",
    "Till I Collapse Eminem",
    "Power Kanye West",
    "We Will Rock You Queen",
    "Don't Stop Believin' Journey",
    "Livin' on a Prayer Bon Jovi",
    "Welcome to the Jungle Guns N' Roses",
    "Back in Black AC/DC",
    "Eye of the Tiger Survivor",
    "Remember the Name Fort Minor",
    "Centuries Fall Out Boy",
    "Believer Imagine Dragons",
    "Thunder Imagine Dragons",
    
    # Hip Hop/Rap
    "HUMBLE Kendrick Lamar",
    "Sicko Mode Travis Scott",
    "God's Plan Drake",
    "Hotline Bling Drake",
    "Old Town Road Lil Nas X",
    "Savage Megan Thee Stallion",
    "WAP Cardi B",
    "In Da Club 50 Cent",
    "Lose Yourself Eminem",
    "Stan Eminem",
    "Juicy The Notorious BIG",
    "California Love 2Pac",
    "Gin and Juice Snoop Dogg",
    "Hey Ya OutKast",
    "Gold Digger Kanye West",
    "Empire State of Mind Jay-Z",
    "Alright Kendrick Lamar",
    "Money Trees Kendrick Lamar",
    "No Role Modelz J Cole",
    "Swimming Pools Kendrick Lamar",
    
    # R&B/Soul
    "Superstition Stevie Wonder",
    "Respect Aretha Franklin",
    "I Want You Back Jackson 5",
    "Ain't No Mountain High Enough Marvin Gaye",
    "What's Going On Marvin Gaye",
    "Let's Stay Together Al Green",
    "Lean On Me Bill Withers",
    "Redbone Childish Gambino",
    "Thinking Out Loud Ed Sheeran",
    "All of Me John Legend",
    "Earned It The Weeknd",
    "Love on the Brain Rihanna",
    "Adore You Harry Styles",
    "Say So Doja Cat",
    "Peaches Justin Bieber",
    "Leave the Door Open Silk Sonic",
    "No Tears Left to Cry Ariana Grande",
    "Thank U Next Ariana Grande",
    "Positions Ariana Grande",
    "Good Days SZA",
    
    # Electronic/Dance
    "One More Time Daft Punk",
    "Get Lucky Daft Punk",
    "Wake Me Up Avicii",
    "Titanium David Guetta Sia",
    "Animals Martin Garrix",
    "Levels Avicii",
    "Don't You Worry Child Swedish House Mafia",
    "Clarity Zedd",
    "Roses SAINt JHN",
    "Blinding Lights The Weeknd",
    "Starboy The Weeknd",
    "The Hills The Weeknd",
    "Closer The Chainsmokers",
    "Something Just Like This Chainsmokers Coldplay",
    "This Is What You Came For Calvin Harris",
    "Summer Calvin Harris",
    "Spectrum Say My Name Florence Machine",
    "Strobe deadmau5",
    "Language Porter Robinson",
    "Shelter Porter Robinson Madeon",
    
    # Indie/Alternative
    "Take Me Out Franz Ferdinand",
    "Float On Modest Mouse",
    "1901 Phoenix",
    "Electric Feel MGMT",
    "Kids MGMT",
    "Time to Pretend MGMT",
    "Pumped Up Kicks Foster the People",
    "Little Talks Of Monsters and Men",
    "Ho Hey The Lumineers",
    "Riptide Vance Joy",
    "Budapest George Ezra",
    "Somebody Told Me The Killers",
    "Take Me to Church Hozier",
    "High and Dry Radiohead",
    "Fake plastic Trees Radiohead",
    "No Surprises Radiohead",
    "Where Is My Mind Pixies",
    "Maps Yeah Yeah Yeahs",
    "Do I Wanna Know Arctic Monkeys",
    "Fluorescent Adolescent Arctic Monkeys",
    
    # Country
    "Jolene Dolly Parton",
    "9 to 5 Dolly Parton",
    "Ring of Fire Johnny Cash",
    "Take Me Home Country Roads John Denver",
    "Friends in Low Places Garth Brooks",
    "The Dance Garth Brooks",
    "Man I Feel Like a Woman Shania Twain",
    "Before He Cheats Carrie Underwood",
    "Need You Now Lady A",
    "Cruise Florida Georgia Line",
    "Body Like a Back Road Sam Hunt",
    "Die a Happy Man Thomas Rhett",
    "Meant to Be Bebe Rexha Florida Georgia Line",
    "10000 Hours Dan Shay Justin Bieber",
    "Girl Crush Little Big Town",
    "Wagon Wheel Darius Rucker",
    "Chicken Fried Zac Brown Band",
    "Tennessee Whiskey Chris Stapleton",
    "Blue Ain't Your Color Keith Urban",
    "Drunk on a Plane Dierks Bentley",
    
    # Latin/Reggaeton
    "Despacito Luis Fonsi Daddy Yankee",
    "Bailando Enrique Iglesias",
    "Mi Gente J Balvin",
    "Taki Taki DJ Snake",
    "Con Calma Daddy Yankee",
    "Dura Daddy Yankee",
    "X Nicky Jam J Balvin",
    "Felices los 4 Maluma",
    "Callaita Bad Bunny",
    "Safaera Bad Bunny",
    "Dakiti Bad Bunny Jhay Cortez",
    "La Cancion J Balvin Bad Bunny",
    "Yo Perreo Sola Bad Bunny",
    "Loco Contigo DJ Snake J Balvin",
    "Vivir Mi Vida Marc Anthony",
    "Propuesta Indecente Romeo Santos",
    "Obsesión Aventura",
    "Danza Kuduro Don Omar",
    "Gasolina Daddy Yankee",
    "Limbo Daddy Yankee",
    
    # Jazz/Blues
    "What a Wonderful World Louis Armstrong",
    "Fly Me to the Moon Frank Sinatra",
    "My Way Frank Sinatra",
    "Unforgettable Nat King Cole",
    "Summertime Ella Fitzgerald",
    "Feeling Good Nina Simone",
    "At Last Etta James",
    "Take Five Dave Brubeck",
    "So What Miles Davis",
    "All Blues Miles Davis",
    "Round Midnight Thelonious Monk",
    "Mack the Knife Bobby Darin",
    "Beyond the Sea Bobby Darin",
    "The Girl from Ipanema Stan Getz",
    "Sing Sing Sing Benny Goodman",
    "In the Mood Glenn Miller",
    "Cheek to Cheek Ella Fitzgerald",
    "Autumn Leaves Nat King Cole",
    "Blue in Green Bill Evans",
    "Dream a Little Dream The Mamas Papas",
    
    # More Recent Hits
    "Peaches Justin Bieber",
    "Save Your Tears The Weeknd",
    "Good 4 U Olivia Rodrigo",
    "Montero Lil Nas X",
    "Kiss Me More Doja Cat",
    "Stay The Kid LAROI Justin Bieber",
    "Heat Waves Glass Animals",
    "Shivers Ed Sheeran",
    "Easy on Me Adele",
    "Happier Than Ever Billie Eilish",
    "We Don't Talk About Bruno Encanto",
    "As It Was Harry Styles",
    "First Class Jack Harlow",
    "Running Up That Hill Kate Bush",
    "Anti-Hero Taylor Swift",
    "Flowers Miley Cyrus",
    "Vampire Olivia Rodrigo",
    "Paint The Town Red Doja Cat",
    "Cruel Summer Taylor Swift",
    "Snooze SZA",
    "Greedy Tate McRae",
    
    # Additional Variety
    "Sweet Caroline Neil Diamond",
    "Don't Stop Believin' Journey",
    "Livin' on a Prayer Bon Jovi",
    "I Will Survive Gloria Gaynor",
    "Stayin' Alive Bee Gees",
    "Africa Toto",
    "Total Eclipse of the Heart Bonnie Tyler",
    "Take on Me a-ha",
    "Every Breath You Take The Police",
    "With or Without You U2",
]

if __name__ == "__main__":
    print(f"📋 Generated {len(SONG_QUERIES)} songs")
    print(f"✅ Ready for mood and description generation")
